version: '3.8'

# Infrastructure services - Always running
# Deploy this first via Portainer

services:
  # PostgreSQL Database - Core infrastructure
  postgres:
    image: postgres:15
    container_name: aslan_postgres
    environment:
      POSTGRES_DB: aslan_drive
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-trading123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./generated/migration.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trader -d aslan_drive"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - aslan_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    labels:
      - "traefik.enable=false"
      - "aslan.service=database"
      - "aslan.tier=infrastructure"
      - "aslan.backup=weekly"

  # MD Provider API - Always running
  md_provider:
    build:
      context: .
      dockerfile: docker/Dockerfile.md_provider
    image: aslan_drive_md_provider:latest
    container_name: aslan_md_provider
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://trader:${POSTGRES_PASSWORD:-trading123}@postgres:5432/aslan_drive
      MD_PROVIDER_HOST: 0.0.0.0
      MD_PROVIDER_PORT: 8000
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "${MD_PROVIDER_PORT:-8000}:8000"
    volumes:
      - .:/app
    networks:
      - aslan_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.md-provider.rule=Host(`api.aslan-drive.local`)"
      - "traefik.http.services.md-provider.loadbalancer.server.port=8000"
      - "aslan.service=md-provider"
      - "aslan.tier=api"

volumes:
  postgres_data:
    name: aslan_postgres_data
    external: false
    labels:
      - "aslan.data=postgres"
      - "aslan.backup=required"

networks:
  aslan_network:
    name: aslan_network
    driver: bridge
    external: false
    labels:
      - "aslan.network=main"