apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: aslan-drive
spec:
  encryptedData:
    .dockerconfigjson: AgChicA9w7owEP5zMoj50Bj8IPYXh0Fr3ASYQWtXYFajR4zcreVrGnZhu6/rANIelFu/9EolfsmA0QBBciSC6tszrT3ywyBzaQnUJSQ4Wx/pN1GEgD99Ji/tdsNvaUWSsgQb7C0Qj3815+YSqYMA2W7Lp6TwqqbQsmBnoI8ewkbKEQomeR5kPPe5FvrPOwjAUOkPrdTReLCrqfkCSrkNuhGk06OfzJ+ulmelxv5G7reHX4yrLwJ+Gw3giDcH6TPXEMCa+3xI4EEhckzwWzqTgrjE5n7kFnx4lyH6ropaom/G7KUKmhj/as4sL87UsdvVXpuCgBlLnAOH/AbNTKloQG+ZB0ci7Lkj7n6HIgtmGjrER2Dn7zyOq2rTmEuwoO9P3Opxxq1ZJfX0ln2WzzTQqg2ekJzjE777nWl7sIviHZzp0QdppZT/4DEAez1i66FiZ2NyZLV3z9UQY8erj5RquqLl2fZKLqsznDb1NZGjh+Vh8djViOQZF36SvE0EFHzThpcxyusLKiOB62ug7DaX6Gp3WeZro7flo4UcD1e+tMqOzRQtbqJngYG3DyhGu7QV4/f51qcw/h+0xrAWsRhRedr1f+AjucsE6Mv7pbXaKBGG5BMXhqYAUyLMZE9HBJWy0BQ6NgKKiCa2kMS+Z82LTQqHwdzCT158M5i9GPoyHvMLXw2OGpiSC7xF0j7adBozAv5mDnu2xaXyVvIJdwuAV5ZC6M2NUpJC8aVlB9RPCHiF+lVGM4IPAgwlaEyOhjX32dACiJrcxZ0Rb0aMB9gZW+sA+TQWZHYAGEI3U6/Npz9SbDyQF7X6iJzpmzn/XjOi1deRNc3uT0a91fCxJ3KyI09HZAv07C9YhNLPbxoaeGFIrySf9c+DiTIs+tfd2KYWXB1D6S9d4Ae1Tz8RE7RkHNhD/xsuOPKNZulSECSje4Rx+bDzFuVUAxQJGE9OMOXlE3vHA6xLmIcnCDC6YVVs7XWz+PNXtc9ngHB7xVgEpJBEU6B5vcdX60PYaUFdUVMvRvrth2SxpyDG/BcqDHmdLDq4X5o6L9AVeOxaqunLgat/0+1abTFpYE1CJfRqYWQpKZaJi8eU5pR4dPhuvxz4l5pHMHK1uJhU78+PsgqLI3fv/tw=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: aslan-drive
    type: kubernetes.io/dockerconfigjson
---
