apiVersion: v1
kind: Secret
metadata:
  name: aslan-drive-secrets
  namespace: aslan-drive
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded secrets
  # echo -n "postgresql://user:password@postgres:5432/aslan_drive" | base64
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9hc2xhbl9kcml2ZQ==
  # echo -n "https://hooks.slack.com/your/webhook/url" | base64  
  slack-webhook-url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20veW91ci93ZWJob29rL3VybA==