"""Initial schema with daily_ohlcv and symbols tables

Revision ID: 642f5b56bb73
Revises: 
Create Date: 2025-09-04 19:35:54.042805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '642f5b56bb73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbols',
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Financial instrument symbol (e.g., AAPL, EURUSD)'),
    sa.Column('name', sa.String(length=255), nullable=True, comment="Full name of the instrument (e.g., 'Apple Inc.')"),
    sa.Column('asset_class', sa.String(length=50), nullable=False, comment='Asset class (equity, forex, crypto, etc.)'),
    sa.Column('exchange', sa.String(length=50), nullable=True, comment='Primary exchange (e.g., NASDAQ, NYSE)'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Base currency (e.g., USD, EUR)'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='Whether symbol is actively tracked'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last updated timestamp'),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('daily_ohlcv',
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Financial instrument symbol (e.g., AAPL, EURUSD)'),
    sa.Column('date', sa.Date(), nullable=False, comment='Trading date'),
    sa.Column('open', sa.Numeric(precision=15, scale=4), nullable=False, comment='Opening price'),
    sa.Column('high', sa.Numeric(precision=15, scale=4), nullable=False, comment='Highest price during the trading day'),
    sa.Column('low', sa.Numeric(precision=15, scale=4), nullable=False, comment='Lowest price during the trading day'),
    sa.Column('close', sa.Numeric(precision=15, scale=4), nullable=False, comment='Closing price'),
    sa.Column('volume', sa.BigInteger(), nullable=False, comment='Trading volume'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_ohlcv')
    op.drop_table('symbols')
    # ### end Alembic commands ###