---
# PostgREST Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aslan-postgrest
  namespace: aslan-drive
  labels:
    app: aslan-drive
    component: postgrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aslan-drive
      component: postgrest
  template:
    metadata:
      labels:
        app: aslan-drive
        component: postgrest
    spec:
      containers:
      - name: postgrest
        image: postgrest/postgrest:v12.2.3
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: PGRST_DB_URI
          valueFrom:
            secretKeyRef:
              name: aslan-drive-secrets
              key: database-url
        - name: PGRST_DB_SCHEMAS
          value: "public"
        - name: PGRST_DB_ANON_ROLE
          value: "trader"
        - name: PGRST_SERVER_PORT
          value: "3000"
        - name: PGRST_SERVER_HOST
          value: "*"
        - name: PGRST_OPENAPI_SERVER_PROXY_URI
          value: "http://localhost:30300"
        - name: PGRST_OPENAPI_MODE
          value: "follow-privileges"
        - name: PGRST_LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
# PostgREST Service with NodePort
apiVersion: v1
kind: Service
metadata:
  name: aslan-postgrest-service
  namespace: aslan-drive
  labels:
    app: aslan-drive
    component: postgrest
spec:
  type: NodePort
  selector:
    app: aslan-drive
    component: postgrest
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
    protocol: TCP
    name: http