# Portainer Stack: Aslan Drive Infrastructure
# Deploy this stack first for always-running services
#
# Stack Name: aslan-infrastructure
# Description: PostgreSQL database, MD Provider API, and pgAdmin frontend

version: '3.8'
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: aslan_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-supersecret}
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
    labels:
      - "aslan.service=pgadmin"
      - "aslan.tier=frontend"

volumes:
  pgadmin_data:
    name: aslan_pgadmin_data

