# Portainer Stack: Aslan Drive Infrastructure
# Deploy this stack first - contains always-running services
#
# Stack Name: aslan-infrastructure
# Description: Core infrastructure (PostgreSQL + API)

version: '3.8'

services:
  # PostgreSQL Database - Core infrastructure
  postgres:
    image: postgres:15
    container_name: aslan_postgres
    environment:
      POSTGRES_DB: aslan_drive
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # NOTE: Upload migration.sql via Portainer file manager to /data/migration.sql
      - /data/migration.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trader -d aslan_drive"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - aslan_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    labels:
      - "traefik.enable=false"
      - "aslan.service=database"
      - "aslan.tier=infrastructure"
      - "aslan.backup=weekly"

  # MD Provider API - Always running
  md_provider:
    image: ${DOCKER_REGISTRY:-}aslan_drive_md_provider:${IMAGE_TAG:-latest}
    container_name: aslan_md_provider
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://trader:${POSTGRES_PASSWORD}@postgres:5432/aslan_drive
      MD_PROVIDER_HOST: 0.0.0.0
      MD_PROVIDER_PORT: 8000
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "${MD_PROVIDER_PORT:-8000}:8000"
    networks:
      - aslan_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.md-provider.rule=Host(`${API_DOMAIN:-api.aslan-drive.local}`)"
      - "traefik.http.services.md-provider.loadbalancer.server.port=8000"
      - "aslan.service=md-provider"
      - "aslan.tier=api"

volumes:
  postgres_data:
    name: aslan_postgres_data
    labels:
      - "aslan.data=postgres"
      - "aslan.backup=required"

networks:
  aslan_network:
    name: aslan_network
    driver: bridge
    labels:
      - "aslan.network=main"