# Portainer Stack: Aslan Drive Scheduled Jobs (Local Build for ARM64)
# Use this for manual job execution on ARM64 architecture
# This builds images locally from source code
#
# Stack Name: aslan-scheduled-jobs-local
# Description: Manual execution containers for data ingestion and health checks

version: '3.8'

services:
  # Data Ingestion Job - Manual execution container (built locally)
  data_ingestion:
    build:
      context: .
      dockerfile: services/data_ingestion/Dockerfile
    container_name: aslan_data_ingestion_manual
    environment:
      DATABASE_URL: postgresql://trader:${POSTGRES_PASSWORD}@postgres:5432/aslan_drive
      LOG_LEVEL: ${LOG_LEVEL:-info}
      CONTINUOUS_MODE: "false"
    networks:
      - aslan_network
    restart: "no"  # Don't auto-restart - job should complete
    profiles:
      - manual-execution
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
        reservations:
          memory: 128M
          cpus: '0.1'
      restart_policy:
        condition: none
    labels:
      - "aslan.service=data-ingestion"
      - "aslan.tier=processing"
      - "aslan.execution=manual"
      - "portainer.job.description=Run daily data ingestion manually (ARM64 local build)"
      - "portainer.job.schedule=Daily at 6:00 AM"

  # Health Check Job - Manual execution container (built locally)
  health_check:
    build:
      context: .
      dockerfile: services/health_check/Dockerfile
    container_name: aslan_health_check_manual
    environment:
      DATABASE_URL: postgresql://trader:${POSTGRES_PASSWORD}@postgres:5432/aslan_drive
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL:-}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      CONTINUOUS_MODE: "false"
    networks:
      - aslan_network
    restart: "no"  # Don't auto-restart - job should complete
    profiles:
      - manual-execution
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
        reservations:
          memory: 64M
          cpus: '0.05'
      restart_policy:
        condition: none
    labels:
      - "aslan.service=health-check"
      - "aslan.tier=monitoring"
      - "aslan.execution=manual"
      - "portainer.job.description=Run database health check manually (ARM64 local build)"
      - "portainer.job.schedule=Daily at 8:00 AM"

networks:
  aslan_network:
    name: aslan_network
    external: true